# Generated by Django 3.2.12 on 2022-03-09 20:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('selectManufacturer', models.CharField(choices=[('Texecom', 'Texecom'), ('Vighanharta', 'Vighanharta')], max_length=100)),
                ('slugName', models.CharField(max_length=30)),
                ('deviceID', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('ipAddress', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selectBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.branch')),
            ],
            options={
                'verbose_name_plural': 'Panel',
            },
        ),
        migrations.CreateModel(
            name='PanelInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('armStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('zoneStatus', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.panel')),
            ],
        ),
        migrations.CreateModel(
            name='NVR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('selectManufacturer', models.CharField(choices=[('Hikvision', 'Hikvision'), ('Milesight', 'Milesight'), ('Dahua', 'Dahua')], max_length=100)),
                ('slugName', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ipAddress', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('playbackUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selectBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.branch')),
            ],
            options={
                'verbose_name_plural': 'NVR',
            },
        ),
        migrations.CreateModel(
            name='InfoNVR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('deviceID', models.CharField(blank=True, max_length=200, null=True)),
                ('macAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('modelNo', models.CharField(blank=True, max_length=100, null=True)),
                ('hddCapacity', models.CharField(blank=True, max_length=100, null=True)),
                ('freeHdd', models.CharField(blank=True, max_length=100, null=True)),
                ('hddType', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nvr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.nvr')),
            ],
        ),
    ]
